 variable "app_name" {
  type        = string
  default     = "petclinic"
  description = "app name"
}

 variable "app_environment" {
  type        = string
  default     = "petclinic project"
  description = "app environment"
}
 
 variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair1"
  description = "Key-pair generated by Terraform"
}
 
variable "key_name" {
  type        = string
  default     = "petclinic_key"
  description = "key name"
}

variable "instance_type" {
  type        = string
  default     = "t2.micro"
  description = "instance type"
}
 
variable "ami" {
  type        = string
  default     = "ami-0d527b8c289b4af7f"
  description = "instance ami"
}

variable "db_private_ips" {
  type        = string
  default     = "10.0.1.238"
  description = "db private ips"
}

variable "aws_region" {
  type        = string
  default     = "eu-central-1"
  description = "The AWS region to create things in."
}

variable "container_port" {
  type        = string
  default     = 8080
  description = "Port exposed by the docker image to redirect traffic to"
}

variable "host_port" {
  type        = string
  default     = 8080 
  description = "Port exposed by the docker image to redirect traffic to"
}

variable "task_count" {
  type        = string
  default     = 1 
  description = "Number of ECS tasks to run"
}

variable "fargate_cpu" {
  type        = string
  default     = "512"
  description = "Fargate instance CPU units to provision"
}

variable "fargate_memory" {
  type        = string
  default     = "1024"
  description = "Fargate instance memory to provision (in MiB)"
}
 
#variable "task_envs" {
#  type        = any
#  description = "The policy document. This is a JSON formatted string."
#  default =   [
#              {
#                "name" : "spring.profiles.active",
#                "value" : "mysql"
#              },
#              {
#                "name" : "MYSQL_USER",
#                "value" : "petclinic"
#              },
#              {
#                "name" : "MYSQL_PASSWORD",
#                "value" : "petclinic"
#              },
#              {
#                "name" : "MYSQL_URL",
#                "value" : "jdbc:mysql://10-0-1-238/petclinic"
#              }]
#}
